# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm audit
  displayName: 'Dependency Audit'

- script: npm run lint
  displayName: 'Lint Code'

- script: npm run test
  displayName: 'Unit Tests'

- script: npm run coveralls
  displayName: 'Publish Coverage to Coveralls.io'
  env:
    COVERALLS_SERVICE_NAME: 'Azure Pipelines'
    COVERALLS_SERVICE_JOB_ID: ${Build.BuildId}

# - task: PublishCodeCoverageResults@1
#   displayName: 'Publish Code Coverage'
#   env:
#     COVERALLS_SERVICE_NAME: 'Azure Pipelines'
#     COVERALLS_SERVICE_JOB_ID: ${Build.BuildId}
#   inputs:
#     codeCoverageTool: cobertura
#     summaryFileLocation: './coverage/cobertura-coverage.xml'
#     reportDirectory: './coverage/lcov-report'
#     #additionalCodeCoverageFiles: # Optional
#     #failIfCoverageEmpty: false # Optional
